### ISSUE TITLE
I want Translate mina website into Chinese, what should I do to help?

### ISSUE THREAD

**Issue by 1c7** [mina-deploy/mina-docs#6]
maybe fork this repo & change file under `source/` folder?
what exactly I should do?

is http://nadarei.co/mina run on Github Page?

**Comment by sobrinho** [comment]
Hey @1c7, are you still interested on that?

If so, I would be glad to help.

**Comment by 1c7** [comment]
@sobrinho 
Sorry :( 
I don't have time at this point.
actually this is my first day of 2 week plan..
I have a bit free time.
I am trying to find a niche and see if I could build business on it.
should be fun. 

I get back to you once I want translate mina again :D 

Mina is great tool. Thank you for that!
I am using mina deploy all my Rails project.

**Comment by 1c7** [comment]
let me close this issue. I would reopen it once I want translate mina ;D
Thank you
